/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rainscape;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ezekiel
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        content_box_scroll.getVerticalScrollBar().setUnitIncrement(16);
        sidebar_box.setVisible(false);
        
        WeatherAPI.fetch(WeatherAPI.currentUserArea());
        TropicalCyclone.fetch();
        
        WeatherAPI.setValues();
        DateTime.setValues();
        TropicalCyclone.setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content_box_scroll = new javax.swing.JScrollPane();
        content_box = new javax.swing.JPanel();
        mainBanner = new javax.swing.JPanel();
        basicforecast_box = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        temp = new javax.swing.JLabel();
        localdate = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        localtime = new javax.swing.JLabel();
        searchbar_bg = new javax.swing.JPanel();
        searchbar = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        hamburger_box = new javax.swing.JPanel();
        line1 = new javax.swing.JPanel();
        line2 = new javax.swing.JPanel();
        line3 = new javax.swing.JPanel();
        line4 = new javax.swing.JPanel();
        line5 = new javax.swing.JPanel();
        sidebar_box = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        logout = new javax.swing.JButton();
        account = new javax.swing.JButton();
        appearance = new javax.swing.JButton();
        rainscape = new javax.swing.JButton();
        tabbed_content = new javax.swing.JTabbedPane();
        weather_box = new javax.swing.JPanel();
        typhoon_box = new javax.swing.JPanel();
        typhoon_image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tcadvisory = new javax.swing.JButton();
        records2021 = new javax.swing.JButton();
        records2020 = new javax.swing.JButton();
        records2019 = new javax.swing.JButton();
        records2018 = new javax.swing.JButton();
        records2017 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RainScape");
        setMinimumSize(new java.awt.Dimension(1200, 675));
        setName(""); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 675));

        content_box_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        content_box_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        content_box_scroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        content_box_scroll.setFocusable(false);
        content_box_scroll.setPreferredSize(new java.awt.Dimension(1200, 675));
        content_box_scroll.setRequestFocusEnabled(false);

        content_box.setBackground(new java.awt.Color(51, 51, 51));
        content_box.setForeground(new java.awt.Color(0, 0, 0));
        content_box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content_box.setPreferredSize(new java.awt.Dimension(1188, 925));

        mainBanner.setBackground(new java.awt.Color(153, 204, 255));
        mainBanner.setPreferredSize(new java.awt.Dimension(1188, 250));

        basicforecast_box.setBackground(new java.awt.Color(51, 51, 51));
        basicforecast_box.setForeground(new java.awt.Color(51, 51, 51));
        basicforecast_box.setFocusable(false);

        status.setBackground(new java.awt.Color(237, 249, 244));
        status.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        status.setForeground(new java.awt.Color(237, 249, 244));
        status.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        status.setText("Xxxxx xxxxxx");

        temp.setBackground(new java.awt.Color(237, 249, 244));
        temp.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        temp.setForeground(new java.awt.Color(237, 249, 244));
        temp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temp.setText("XX.X°");

        localdate.setBackground(new java.awt.Color(237, 249, 244));
        localdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        localdate.setForeground(new java.awt.Color(237, 249, 244));
        localdate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        localdate.setText("XX/XX/XXXX");

        location.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        location.setForeground(new java.awt.Color(237, 249, 244));
        location.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        location.setText("XXXXXX, XXXXXX");

        javax.swing.GroupLayout basicforecast_boxLayout = new javax.swing.GroupLayout(basicforecast_box);
        basicforecast_box.setLayout(basicforecast_boxLayout);
        basicforecast_boxLayout.setHorizontalGroup(
            basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicforecast_boxLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(localdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        basicforecast_boxLayout.setVerticalGroup(
            basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicforecast_boxLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basicforecast_boxLayout.createSequentialGroup()
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainBannerLayout = new javax.swing.GroupLayout(mainBanner);
        mainBanner.setLayout(mainBannerLayout);
        mainBannerLayout.setHorizontalGroup(
            mainBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBannerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(basicforecast_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(719, Short.MAX_VALUE))
        );
        mainBannerLayout.setVerticalGroup(
            mainBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBannerLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(basicforecast_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        body.setBackground(new java.awt.Color(225, 230, 236));
        body.setForeground(new java.awt.Color(225, 230, 236));
        body.setPreferredSize(new java.awt.Dimension(1188, 675));

        menuBar.setBackground(new java.awt.Color(0, 51, 51));

        localtime.setBackground(new java.awt.Color(237, 249, 244));
        localtime.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        localtime.setForeground(new java.awt.Color(237, 249, 244));
        localtime.setText("XX:XX:XX XX");

        searchbar_bg.setBackground(new java.awt.Color(16, 27, 25));
        searchbar_bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        searchbar_bg.setMaximumSize(new java.awt.Dimension(322, 44));
        searchbar_bg.setMinimumSize(new java.awt.Dimension(322, 44));
        searchbar_bg.setPreferredSize(new java.awt.Dimension(426, 36));

        searchbar.setBackground(new java.awt.Color(16, 27, 25));
        searchbar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchbar.setForeground(new java.awt.Color(225, 230, 236));
        searchbar.setBorder(null);
        searchbar.setCaretColor(new java.awt.Color(102, 102, 102));
        searchbar.setNextFocusableComponent(searchbutton);
        searchbar.setOpaque(true);
        searchbar.setPreferredSize(new java.awt.Dimension(300, 36));
        searchbar.setSelectionColor(new java.awt.Color(0, 153, 153));
        searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchbarKeyPressed(evt);
            }
        });

        searchbutton.setBackground(new java.awt.Color(51, 51, 51));
        searchbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton.setText("Search");
        searchbutton.setBorder(null);
        searchbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton.setNextFocusableComponent(searchbar);
        searchbutton.setPreferredSize(new java.awt.Dimension(110, 36));
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchbar_bgLayout = new javax.swing.GroupLayout(searchbar_bg);
        searchbar_bg.setLayout(searchbar_bgLayout);
        searchbar_bgLayout.setHorizontalGroup(
            searchbar_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchbar_bgLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        searchbar_bgLayout.setVerticalGroup(
            searchbar_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchbar_bgLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(searchbar_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        hamburger_box.setBackground(new java.awt.Color(0, 0, 0));
        hamburger_box.setForeground(new java.awt.Color(0, 0, 0));
        hamburger_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hamburger_box.setOpaque(false);
        hamburger_box.setPreferredSize(new java.awt.Dimension(36, 35));
        hamburger_box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hamburger_boxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hamburger_boxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hamburger_boxMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hamburger_boxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hamburger_boxMouseReleased(evt);
            }
        });

        line1.setBackground(new java.awt.Color(255, 255, 255));
        line1.setForeground(new java.awt.Color(255, 255, 255));
        line1.setPreferredSize(new java.awt.Dimension(22, 5));

        javax.swing.GroupLayout line1Layout = new javax.swing.GroupLayout(line1);
        line1.setLayout(line1Layout);
        line1Layout.setHorizontalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        line1Layout.setVerticalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        line2.setBackground(new java.awt.Color(255, 255, 255));
        line2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout line2Layout = new javax.swing.GroupLayout(line2);
        line2.setLayout(line2Layout);
        line2Layout.setHorizontalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        line2Layout.setVerticalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        line3.setBackground(new java.awt.Color(255, 255, 255));
        line3.setForeground(new java.awt.Color(255, 255, 255));
        line3.setPreferredSize(new java.awt.Dimension(32, 5));

        javax.swing.GroupLayout line3Layout = new javax.swing.GroupLayout(line3);
        line3.setLayout(line3Layout);
        line3Layout.setHorizontalGroup(
            line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        line3Layout.setVerticalGroup(
            line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        line4.setBackground(new java.awt.Color(255, 255, 255));
        line4.setForeground(new java.awt.Color(255, 255, 255));
        line4.setPreferredSize(new java.awt.Dimension(20, 5));

        javax.swing.GroupLayout line4Layout = new javax.swing.GroupLayout(line4);
        line4.setLayout(line4Layout);
        line4Layout.setHorizontalGroup(
            line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        line4Layout.setVerticalGroup(
            line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        line5.setBackground(new java.awt.Color(255, 255, 255));
        line5.setForeground(new java.awt.Color(255, 255, 255));
        line5.setPreferredSize(new java.awt.Dimension(10, 5));

        javax.swing.GroupLayout line5Layout = new javax.swing.GroupLayout(line5);
        line5.setLayout(line5Layout);
        line5Layout.setHorizontalGroup(
            line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        line5Layout.setVerticalGroup(
            line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hamburger_boxLayout = new javax.swing.GroupLayout(hamburger_box);
        hamburger_box.setLayout(hamburger_boxLayout);
        hamburger_boxLayout.setHorizontalGroup(
            hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hamburger_boxLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(hamburger_boxLayout.createSequentialGroup()
                        .addComponent(line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hamburger_boxLayout.createSequentialGroup()
                        .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(line2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        hamburger_boxLayout.setVerticalGroup(
            hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hamburger_boxLayout.createSequentialGroup()
                .addGroup(hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(localtime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchbar_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(hamburger_box, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(localtime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchbar_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hamburger_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        sidebar_box.setBackground(new java.awt.Color(255, 255, 255));
        sidebar_box.setForeground(new java.awt.Color(255, 255, 255));
        sidebar_box.setPreferredSize(new java.awt.Dimension(180, 620));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 102, 102));
        logout.setText("   Log Out");
        logout.setBorder(null);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setFocusable(false);
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setPreferredSize(new java.awt.Dimension(138, 50));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        account.setBackground(new java.awt.Color(255, 255, 255));
        account.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        account.setForeground(new java.awt.Color(0, 102, 102));
        account.setText("   Account");
        account.setBorder(null);
        account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        account.setFocusable(false);
        account.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        account.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        account.setPreferredSize(new java.awt.Dimension(138, 50));
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });

        appearance.setBackground(new java.awt.Color(255, 255, 255));
        appearance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        appearance.setForeground(new java.awt.Color(0, 102, 102));
        appearance.setText("   Appearance");
        appearance.setBorder(null);
        appearance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appearance.setFocusable(false);
        appearance.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        appearance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appearance.setPreferredSize(new java.awt.Dimension(138, 50));
        appearance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appearanceActionPerformed(evt);
            }
        });

        rainscape.setBackground(new java.awt.Color(255, 255, 255));
        rainscape.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rainscape.setForeground(new java.awt.Color(0, 102, 102));
        rainscape.setText("   RainScape");
        rainscape.setBorder(null);
        rainscape.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rainscape.setFocusable(false);
        rainscape.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rainscape.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rainscape.setPreferredSize(new java.awt.Dimension(138, 50));
        rainscape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rainscapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebar_boxLayout = new javax.swing.GroupLayout(sidebar_box);
        sidebar_box.setLayout(sidebar_boxLayout);
        sidebar_boxLayout.setHorizontalGroup(
            sidebar_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar_boxLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(sidebar_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appearance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(rainscape, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        sidebar_boxLayout.setVerticalGroup(
            sidebar_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar_boxLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(appearance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rainscape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        tabbed_content.setBackground(new java.awt.Color(255, 255, 255));
        tabbed_content.setForeground(new java.awt.Color(0, 51, 51));
        tabbed_content.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabbed_content.setPreferredSize(new java.awt.Dimension(920, 540));

        weather_box.setBackground(new java.awt.Color(255, 255, 255));
        weather_box.setForeground(new java.awt.Color(255, 255, 255));
        weather_box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        weather_box.setPreferredSize(new java.awt.Dimension(918, 507));

        javax.swing.GroupLayout weather_boxLayout = new javax.swing.GroupLayout(weather_box);
        weather_box.setLayout(weather_boxLayout);
        weather_boxLayout.setHorizontalGroup(
            weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        weather_boxLayout.setVerticalGroup(
            weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        tabbed_content.addTab("         Weather Dashboard                                                                                                   ", weather_box);

        typhoon_box.setBackground(new java.awt.Color(255, 255, 255));
        typhoon_box.setForeground(new java.awt.Color(255, 255, 255));
        typhoon_box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        typhoon_box.setPreferredSize(new java.awt.Dimension(918, 507));

        typhoon_image.setToolTipText("");
        typhoon_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        typhoon_image.setPreferredSize(new java.awt.Dimension(520, 405));
        typhoon_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typhoon_imageMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Latest Tropical Cyclone Advisory (PAGASA)");
        jLabel1.setPreferredSize(new java.awt.Dimension(620, 34));

        tcadvisory.setBackground(new java.awt.Color(255, 255, 255));
        tcadvisory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tcadvisory.setForeground(new java.awt.Color(0, 102, 102));
        tcadvisory.setText("Latest Details");
        tcadvisory.setBorder(null);
        tcadvisory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tcadvisory.setFocusable(false);
        tcadvisory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tcadvisory.setPreferredSize(new java.awt.Dimension(138, 50));
        tcadvisory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcadvisoryActionPerformed(evt);
            }
        });

        records2021.setBackground(new java.awt.Color(255, 255, 255));
        records2021.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2021.setForeground(new java.awt.Color(0, 102, 102));
        records2021.setText("2021 Records");
        records2021.setBorder(null);
        records2021.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2021.setFocusable(false);
        records2021.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2021.setPreferredSize(new java.awt.Dimension(138, 50));
        records2021.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2021ActionPerformed(evt);
            }
        });

        records2020.setBackground(new java.awt.Color(255, 255, 255));
        records2020.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2020.setForeground(new java.awt.Color(0, 102, 102));
        records2020.setText("2020 Records");
        records2020.setBorder(null);
        records2020.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2020.setFocusable(false);
        records2020.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2020.setPreferredSize(new java.awt.Dimension(138, 50));
        records2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2020ActionPerformed(evt);
            }
        });

        records2019.setBackground(new java.awt.Color(255, 255, 255));
        records2019.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2019.setForeground(new java.awt.Color(0, 102, 102));
        records2019.setText("2019 Records");
        records2019.setBorder(null);
        records2019.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2019.setFocusable(false);
        records2019.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2019.setPreferredSize(new java.awt.Dimension(138, 50));
        records2019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2019ActionPerformed(evt);
            }
        });

        records2018.setBackground(new java.awt.Color(255, 255, 255));
        records2018.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2018.setForeground(new java.awt.Color(0, 102, 102));
        records2018.setText("2018 Records");
        records2018.setActionCommand("2018 Records");
        records2018.setBorder(null);
        records2018.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2018.setFocusable(false);
        records2018.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2018.setPreferredSize(new java.awt.Dimension(138, 50));
        records2018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2018ActionPerformed(evt);
            }
        });

        records2017.setBackground(new java.awt.Color(255, 255, 255));
        records2017.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2017.setForeground(new java.awt.Color(0, 102, 102));
        records2017.setText("2017 Records");
        records2017.setActionCommand("2017 Records");
        records2017.setBorder(null);
        records2017.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2017.setFocusable(false);
        records2017.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2017.setPreferredSize(new java.awt.Dimension(138, 50));
        records2017.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2017ActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout typhoon_boxLayout = new javax.swing.GroupLayout(typhoon_box);
        typhoon_box.setLayout(typhoon_boxLayout);
        typhoon_boxLayout.setHorizontalGroup(
            typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typhoon_boxLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(typhoon_boxLayout.createSequentialGroup()
                        .addComponent(typhoon_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(records2018, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(records2017, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tcadvisory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(records2021, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(records2020, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(records2019, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        typhoon_boxLayout.setVerticalGroup(
            typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typhoon_boxLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(typhoon_boxLayout.createSequentialGroup()
                        .addComponent(tcadvisory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(records2021, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(records2020, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(records2019, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(records2018, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(records2017, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(typhoon_boxLayout.createSequentialGroup()
                        .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5)
                            .addComponent(typhoon_image, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                        .addGap(29, 29, 29))))
        );

        tabbed_content.addTab("           Tropical Cyclone Dashboard                                                                                       ", typhoon_box);

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabbed_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sidebar_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(sidebar_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tabbed_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout content_boxLayout = new javax.swing.GroupLayout(content_box);
        content_box.setLayout(content_boxLayout);
        content_boxLayout.setHorizontalGroup(
            content_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        content_boxLayout.setVerticalGroup(
            content_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, content_boxLayout.createSequentialGroup()
                .addComponent(mainBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        content_box_scroll.setViewportView(content_box);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content_box_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(content_box_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchProcess(String area) {
        if (area.equals("")) {
            WeatherAPI.current_area = "";
            WeatherAPI.fetch(WeatherAPI.currentUserArea());
        } else if (!WeatherAPI.current_area.equals(area)){
            WeatherAPI.current_area = area;
            WeatherAPI.fetch(WeatherAPI.currentUserArea());
        }
        
        WeatherAPI.setValues();
        searchbar.setText("");
        
        searchbutton.nextFocus();
    }
    
    private void hamburgerToggle(boolean active) {
        if (active) {
            line1.setBackground(Color.lightGray);
            line2.setBackground(Color.lightGray);
            line3.setBackground(Color.lightGray);
            
            if (!sidebar_box.isVisible()) {
                line4.setBackground(Color.lightGray);
                line5.setBackground(Color.lightGray);
            } else {
                line4.setBackground(menuBar.getBackground());
                line5.setBackground(menuBar.getBackground());
            }
        } else {
            line1.setBackground(line1.getForeground());
            line2.setBackground(line1.getForeground());
            line3.setBackground(line1.getForeground());
            
            if (!sidebar_box.isVisible()) {
                line4.setBackground(line1.getForeground());
                line5.setBackground(line1.getForeground());
            } else {
                line4.setBackground(menuBar.getBackground());
                line5.setBackground(menuBar.getBackground());
            }
        }
    }
    
    private void sidebarToggle() {
        if (sidebar_box.isVisible()) {
            sidebar_box.setVisible(false);
            
            line4.setBackground(Color.lightGray);
            line5.setBackground(Color.lightGray);
        } else if (!sidebar_box.isVisible()) {
            sidebar_box.setVisible(true);
            
            line4.setBackground(menuBar.getBackground());
            line5.setBackground(menuBar.getBackground());
        }
    }
    
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        LoginGUI.main(null);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void searchbarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            searchProcess(searchbar.getText());
        }
    }//GEN-LAST:event_searchbarKeyPressed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
        searchProcess(searchbar.getText());
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void hamburger_boxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMouseEntered
        // TODO add your handling code here:
        hamburgerToggle(true);
    }//GEN-LAST:event_hamburger_boxMouseEntered

    private void hamburger_boxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMouseExited
        // TODO add your handling code here:
        hamburgerToggle(false);
    }//GEN-LAST:event_hamburger_boxMouseExited

    private void hamburger_boxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMousePressed
        // TODO add your handling code here:
        hamburgerToggle(false);
    }//GEN-LAST:event_hamburger_boxMousePressed

    private void hamburger_boxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMouseReleased
        // TODO add your handling code here:
        hamburgerToggle(true);
    }//GEN-LAST:event_hamburger_boxMouseReleased

    private void hamburger_boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMouseClicked
        // TODO add your handling code here:
        sidebarToggle();
    }//GEN-LAST:event_hamburger_boxMouseClicked

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountActionPerformed

    private void appearanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appearanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appearanceActionPerformed

    private void rainscapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rainscapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rainscapeActionPerformed

    private void records2021ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2021ActionPerformed
        TropicalCyclone.openOtherTCA("tca2021");
    }//GEN-LAST:event_records2021ActionPerformed

    private void tcadvisoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcadvisoryActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Proceed to PDF Link?") == 0) {
            RainScape.openWebpage("https://pubfiles.pagasa.dost.gov.ph/tamss/weather/tcadvisory.pdf");
        }
    }//GEN-LAST:event_tcadvisoryActionPerformed

    private void typhoon_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typhoon_imageMouseClicked
        // TODO add your handling code here:
        TropicalCyclone.openBigTCA();
    }//GEN-LAST:event_typhoon_imageMouseClicked

    private void records2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2020ActionPerformed
        // TODO add your handling code here:
        TropicalCyclone.openOtherTCA("tca2020");
    }//GEN-LAST:event_records2020ActionPerformed

    private void records2019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2019ActionPerformed
        // TODO add your handling code here:
        TropicalCyclone.openOtherTCA("tca2019");
    }//GEN-LAST:event_records2019ActionPerformed

    private void records2018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2018ActionPerformed
        // TODO add your handling code here:
        TropicalCyclone.openOtherTCA("tca2018");
    }//GEN-LAST:event_records2018ActionPerformed

    private void records2017ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2017ActionPerformed
        // TODO add your handling code here:
        TropicalCyclone.openOtherTCA("tca2017");
    }//GEN-LAST:event_records2017ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Dark look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println("Look and Feel Exception: " + e);
        }
        
        //</editor-fold>
        
        RainScape.access = true;
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton account;
    private javax.swing.JButton appearance;
    private javax.swing.JPanel basicforecast_box;
    private javax.swing.JPanel body;
    private javax.swing.JPanel content_box;
    private javax.swing.JScrollPane content_box_scroll;
    private javax.swing.JPanel hamburger_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel line1;
    private javax.swing.JPanel line2;
    private javax.swing.JPanel line3;
    private javax.swing.JPanel line4;
    private javax.swing.JPanel line5;
    public static javax.swing.JLabel localdate;
    public static javax.swing.JLabel localtime;
    public static javax.swing.JLabel location;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainBanner;
    private javax.swing.JPanel menuBar;
    private javax.swing.JButton rainscape;
    private javax.swing.JButton records2017;
    private javax.swing.JButton records2018;
    private javax.swing.JButton records2019;
    private javax.swing.JButton records2020;
    private javax.swing.JButton records2021;
    private javax.swing.JTextField searchbar;
    private javax.swing.JPanel searchbar_bg;
    private javax.swing.JButton searchbutton;
    private javax.swing.JPanel sidebar_box;
    public static javax.swing.JLabel status;
    private javax.swing.JTabbedPane tabbed_content;
    private javax.swing.JButton tcadvisory;
    public static javax.swing.JLabel temp;
    private javax.swing.JPanel typhoon_box;
    public static javax.swing.JLabel typhoon_image;
    private javax.swing.JPanel weather_box;
    // End of variables declaration//GEN-END:variables
}
