/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rainscape;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ezekiel
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        content_box_scroll.getVerticalScrollBar().setUnitIncrement(16);
        sidebar_box.setVisible(false);
        
        WeatherAPI.fetch(RainScape.currentSearchArea());
        TropicalCyclone.fetch();
        
        WeatherAPI.setValues();
        DateTime.setValues();
        TropicalCyclone.setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content_box_scroll = new javax.swing.JScrollPane();
        content_box = new javax.swing.JPanel();
        mainBanner = new javax.swing.JPanel();
        basicforecast_box = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        temp = new javax.swing.JLabel();
        current_icon = new javax.swing.JLabel();
        localdate = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        localtime = new javax.swing.JLabel();
        searchbar_bg = new javax.swing.JPanel();
        searchbar = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        hamburger_box = new javax.swing.JPanel();
        line1 = new javax.swing.JPanel();
        line2 = new javax.swing.JPanel();
        line3 = new javax.swing.JPanel();
        line4 = new javax.swing.JPanel();
        line5 = new javax.swing.JPanel();
        sidebar_box = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        preferences = new javax.swing.JButton();
        weatherlogs = new javax.swing.JButton();
        rainscape = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        tabbed_content = new javax.swing.JTabbedPane();
        weather_box = new javax.swing.JPanel();
        weather_label = new javax.swing.JLabel();
        forecast_label = new javax.swing.JLabel();
        forecast0_panel = new javax.swing.JPanel();
        forecast0_date = new javax.swing.JLabel();
        forecast0_temp = new javax.swing.JLabel();
        forecast0_icon = new javax.swing.JLabel();
        forecast1_panel = new javax.swing.JPanel();
        forecast1_date = new javax.swing.JLabel();
        forecast1_temp = new javax.swing.JLabel();
        forecast1_icon = new javax.swing.JLabel();
        forecast2_panel = new javax.swing.JPanel();
        forecast2_date = new javax.swing.JLabel();
        forecast2_temp = new javax.swing.JLabel();
        forecast2_icon = new javax.swing.JLabel();
        cloud_progressbar = new javax.swing.JProgressBar();
        humidity_progressbar = new javax.swing.JProgressBar();
        humidity_label = new javax.swing.JLabel();
        cloud_label = new javax.swing.JLabel();
        refresh_weather = new javax.swing.JButton();
        typhoon_box = new javax.swing.JPanel();
        tc_label = new javax.swing.JLabel();
        typhoon_image = new javax.swing.JLabel();
        tcadvisory = new javax.swing.JButton();
        records2021 = new javax.swing.JButton();
        records2020 = new javax.swing.JButton();
        records2019 = new javax.swing.JButton();
        records2018 = new javax.swing.JButton();
        records2017 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        refresh_tropicalcyclone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RainScape");
        setMinimumSize(new java.awt.Dimension(1200, 675));
        setName(""); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 675));

        content_box_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        content_box_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        content_box_scroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        content_box_scroll.setFocusable(false);
        content_box_scroll.setPreferredSize(new java.awt.Dimension(1200, 675));
        content_box_scroll.setRequestFocusEnabled(false);

        content_box.setBackground(new java.awt.Color(51, 51, 51));
        content_box.setForeground(new java.awt.Color(0, 0, 0));
        content_box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content_box.setPreferredSize(new java.awt.Dimension(1188, 925));

        mainBanner.setBackground(new java.awt.Color(153, 204, 255));
        mainBanner.setPreferredSize(new java.awt.Dimension(1188, 250));

        basicforecast_box.setBackground(new java.awt.Color(51, 51, 51));
        basicforecast_box.setForeground(new java.awt.Color(51, 51, 51));
        basicforecast_box.setFocusable(false);
        basicforecast_box.setMaximumSize(new java.awt.Dimension(1000, 166));
        basicforecast_box.setMinimumSize(new java.awt.Dimension(300, 166));

        status.setBackground(new java.awt.Color(237, 249, 244));
        status.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        status.setForeground(new java.awt.Color(237, 249, 244));
        status.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        status.setText("Xxxxx xxxxxx");
        status.setMaximumSize(new java.awt.Dimension(500, 32));
        status.setMinimumSize(new java.awt.Dimension(50, 32));

        temp.setBackground(new java.awt.Color(237, 249, 244));
        temp.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        temp.setForeground(new java.awt.Color(237, 249, 244));
        temp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temp.setText("XX°");
        temp.setMaximumSize(new java.awt.Dimension(200, 81));
        temp.setPreferredSize(new java.awt.Dimension(101, 110));

        current_icon.setPreferredSize(new java.awt.Dimension(110, 110));

        localdate.setBackground(new java.awt.Color(237, 249, 244));
        localdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        localdate.setForeground(new java.awt.Color(237, 249, 244));
        localdate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        localdate.setText("XX/XX/XXXX");
        localdate.setMaximumSize(new java.awt.Dimension(500, 32));
        localdate.setMinimumSize(new java.awt.Dimension(50, 32));

        location.setBackground(new java.awt.Color(237, 249, 244));
        location.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        location.setForeground(new java.awt.Color(237, 249, 244));
        location.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        location.setText("Xxxxx, Xxxxx");
        location.setMaximumSize(new java.awt.Dimension(500, 32));
        location.setMinimumSize(new java.awt.Dimension(50, 32));

        javax.swing.GroupLayout basicforecast_boxLayout = new javax.swing.GroupLayout(basicforecast_box);
        basicforecast_box.setLayout(basicforecast_boxLayout);
        basicforecast_boxLayout.setHorizontalGroup(
            basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicforecast_boxLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(temp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(current_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(localdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        basicforecast_boxLayout.setVerticalGroup(
            basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicforecast_boxLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicforecast_boxLayout.createSequentialGroup()
                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(current_icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainBannerLayout = new javax.swing.GroupLayout(mainBanner);
        mainBanner.setLayout(mainBannerLayout);
        mainBannerLayout.setHorizontalGroup(
            mainBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBannerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(basicforecast_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(645, Short.MAX_VALUE))
        );
        mainBannerLayout.setVerticalGroup(
            mainBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBannerLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(basicforecast_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        body.setBackground(new java.awt.Color(225, 230, 236));
        body.setForeground(new java.awt.Color(225, 230, 236));
        body.setPreferredSize(new java.awt.Dimension(1188, 675));

        menuBar.setBackground(new java.awt.Color(0, 51, 51));

        localtime.setBackground(new java.awt.Color(237, 249, 244));
        localtime.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        localtime.setForeground(new java.awt.Color(237, 249, 244));
        localtime.setText("XX:XX:XX XX");

        searchbar_bg.setBackground(new java.awt.Color(16, 27, 25));
        searchbar_bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        searchbar_bg.setMaximumSize(new java.awt.Dimension(322, 44));
        searchbar_bg.setMinimumSize(new java.awt.Dimension(322, 44));
        searchbar_bg.setPreferredSize(new java.awt.Dimension(426, 36));

        searchbar.setBackground(new java.awt.Color(16, 27, 25));
        searchbar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchbar.setForeground(new java.awt.Color(225, 230, 236));
        searchbar.setBorder(null);
        searchbar.setCaretColor(new java.awt.Color(102, 102, 102));
        searchbar.setNextFocusableComponent(searchbutton);
        searchbar.setOpaque(true);
        searchbar.setPreferredSize(new java.awt.Dimension(300, 36));
        searchbar.setRequestFocusEnabled(false);
        searchbar.setSelectionColor(new java.awt.Color(0, 153, 153));
        searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchbarKeyPressed(evt);
            }
        });

        searchbutton.setBackground(new java.awt.Color(51, 51, 51));
        searchbutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton.setText("Search");
        searchbutton.setBorder(null);
        searchbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton.setNextFocusableComponent(searchbar);
        searchbutton.setPreferredSize(new java.awt.Dimension(110, 36));
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchbar_bgLayout = new javax.swing.GroupLayout(searchbar_bg);
        searchbar_bg.setLayout(searchbar_bgLayout);
        searchbar_bgLayout.setHorizontalGroup(
            searchbar_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchbar_bgLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        searchbar_bgLayout.setVerticalGroup(
            searchbar_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchbar_bgLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(searchbar_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        hamburger_box.setBackground(new java.awt.Color(0, 0, 0));
        hamburger_box.setForeground(new java.awt.Color(0, 0, 0));
        hamburger_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hamburger_box.setOpaque(false);
        hamburger_box.setPreferredSize(new java.awt.Dimension(36, 35));
        hamburger_box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hamburger_boxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hamburger_boxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hamburger_boxMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hamburger_boxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hamburger_boxMouseReleased(evt);
            }
        });

        line1.setBackground(new java.awt.Color(255, 255, 255));
        line1.setForeground(new java.awt.Color(255, 255, 255));
        line1.setPreferredSize(new java.awt.Dimension(22, 5));

        javax.swing.GroupLayout line1Layout = new javax.swing.GroupLayout(line1);
        line1.setLayout(line1Layout);
        line1Layout.setHorizontalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        line1Layout.setVerticalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        line2.setBackground(new java.awt.Color(255, 255, 255));
        line2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout line2Layout = new javax.swing.GroupLayout(line2);
        line2.setLayout(line2Layout);
        line2Layout.setHorizontalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        line2Layout.setVerticalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        line3.setBackground(new java.awt.Color(255, 255, 255));
        line3.setForeground(new java.awt.Color(255, 255, 255));
        line3.setPreferredSize(new java.awt.Dimension(32, 5));

        javax.swing.GroupLayout line3Layout = new javax.swing.GroupLayout(line3);
        line3.setLayout(line3Layout);
        line3Layout.setHorizontalGroup(
            line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        line3Layout.setVerticalGroup(
            line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        line4.setBackground(new java.awt.Color(255, 255, 255));
        line4.setForeground(new java.awt.Color(255, 255, 255));
        line4.setPreferredSize(new java.awt.Dimension(20, 5));

        javax.swing.GroupLayout line4Layout = new javax.swing.GroupLayout(line4);
        line4.setLayout(line4Layout);
        line4Layout.setHorizontalGroup(
            line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        line4Layout.setVerticalGroup(
            line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        line5.setBackground(new java.awt.Color(255, 255, 255));
        line5.setForeground(new java.awt.Color(255, 255, 255));
        line5.setPreferredSize(new java.awt.Dimension(10, 5));

        javax.swing.GroupLayout line5Layout = new javax.swing.GroupLayout(line5);
        line5.setLayout(line5Layout);
        line5Layout.setHorizontalGroup(
            line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        line5Layout.setVerticalGroup(
            line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hamburger_boxLayout = new javax.swing.GroupLayout(hamburger_box);
        hamburger_box.setLayout(hamburger_boxLayout);
        hamburger_boxLayout.setHorizontalGroup(
            hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hamburger_boxLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(hamburger_boxLayout.createSequentialGroup()
                        .addComponent(line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hamburger_boxLayout.createSequentialGroup()
                        .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(line2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        hamburger_boxLayout.setVerticalGroup(
            hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hamburger_boxLayout.createSequentialGroup()
                .addGroup(hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(hamburger_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(localtime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchbar_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(hamburger_box, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(localtime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchbar_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hamburger_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        sidebar_box.setBackground(new java.awt.Color(255, 255, 255));
        sidebar_box.setForeground(new java.awt.Color(255, 255, 255));
        sidebar_box.setPreferredSize(new java.awt.Dimension(180, 620));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        preferences.setBackground(new java.awt.Color(255, 255, 255));
        preferences.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        preferences.setForeground(new java.awt.Color(0, 102, 102));
        preferences.setText("   Preferences");
        preferences.setBorder(null);
        preferences.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        preferences.setFocusable(false);
        preferences.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        preferences.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        preferences.setPreferredSize(new java.awt.Dimension(138, 50));
        preferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencesActionPerformed(evt);
            }
        });

        weatherlogs.setBackground(new java.awt.Color(255, 255, 255));
        weatherlogs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        weatherlogs.setForeground(new java.awt.Color(0, 102, 102));
        weatherlogs.setText("   Weather Logs");
        weatherlogs.setBorder(null);
        weatherlogs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        weatherlogs.setFocusable(false);
        weatherlogs.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        weatherlogs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        weatherlogs.setPreferredSize(new java.awt.Dimension(138, 50));
        weatherlogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weatherlogsActionPerformed(evt);
            }
        });

        rainscape.setBackground(new java.awt.Color(255, 255, 255));
        rainscape.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rainscape.setForeground(new java.awt.Color(0, 102, 102));
        rainscape.setText("   RainScape");
        rainscape.setBorder(null);
        rainscape.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rainscape.setFocusable(false);
        rainscape.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rainscape.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rainscape.setPreferredSize(new java.awt.Dimension(138, 50));
        rainscape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rainscapeActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 102, 102));
        logout.setText("   Log Out");
        logout.setBorder(null);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setFocusable(false);
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setPreferredSize(new java.awt.Dimension(138, 50));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebar_boxLayout = new javax.swing.GroupLayout(sidebar_box);
        sidebar_box.setLayout(sidebar_boxLayout);
        sidebar_boxLayout.setHorizontalGroup(
            sidebar_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar_boxLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(sidebar_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(preferences, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(rainscape, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weatherlogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        sidebar_boxLayout.setVerticalGroup(
            sidebar_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebar_boxLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(preferences, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(weatherlogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rainscape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        tabbed_content.setBackground(new java.awt.Color(255, 255, 255));
        tabbed_content.setForeground(new java.awt.Color(0, 51, 51));
        tabbed_content.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabbed_content.setFocusable(false);
        tabbed_content.setPreferredSize(new java.awt.Dimension(920, 540));

        weather_box.setBackground(new java.awt.Color(255, 255, 255));
        weather_box.setForeground(new java.awt.Color(255, 255, 255));
        weather_box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        weather_box.setPreferredSize(new java.awt.Dimension(918, 507));

        weather_label.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        weather_label.setForeground(new java.awt.Color(0, 51, 51));
        weather_label.setText("Good [Time of Day], [User].");
        weather_label.setMaximumSize(new java.awt.Dimension(620, 38));
        weather_label.setMinimumSize(new java.awt.Dimension(620, 38));
        weather_label.setPreferredSize(new java.awt.Dimension(620, 38));

        forecast_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        forecast_label.setForeground(new java.awt.Color(0, 51, 51));
        forecast_label.setText("Three Day Weather Forecast");
        forecast_label.setPreferredSize(new java.awt.Dimension(710, 30));

        forecast0_panel.setBackground(new java.awt.Color(255, 255, 255));
        forecast0_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        forecast0_panel.setForeground(new java.awt.Color(225, 230, 236));
        forecast0_panel.setPreferredSize(new java.awt.Dimension(220, 120));

        forecast0_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        forecast0_date.setForeground(new java.awt.Color(0, 51, 51));
        forecast0_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forecast0_date.setText("XXXX-XX-XX");
        forecast0_date.setPreferredSize(new java.awt.Dimension(164, 26));

        forecast0_temp.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        forecast0_temp.setForeground(new java.awt.Color(0, 51, 51));
        forecast0_temp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        forecast0_temp.setText("XX°");
        forecast0_temp.setMaximumSize(new java.awt.Dimension(100, 32));
        forecast0_temp.setMinimumSize(new java.awt.Dimension(10, 32));
        forecast0_temp.setPreferredSize(new java.awt.Dimension(100, 60));

        forecast0_icon.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout forecast0_panelLayout = new javax.swing.GroupLayout(forecast0_panel);
        forecast0_panel.setLayout(forecast0_panelLayout);
        forecast0_panelLayout.setHorizontalGroup(
            forecast0_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forecast0_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(forecast0_panelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(forecast0_temp, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(forecast0_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        forecast0_panelLayout.setVerticalGroup(
            forecast0_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forecast0_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(forecast0_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(forecast0_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forecast0_temp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forecast0_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        forecast1_panel.setBackground(new java.awt.Color(255, 255, 255));
        forecast1_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        forecast1_panel.setForeground(new java.awt.Color(225, 230, 236));
        forecast1_panel.setPreferredSize(new java.awt.Dimension(220, 120));

        forecast1_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        forecast1_date.setForeground(new java.awt.Color(0, 51, 51));
        forecast1_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forecast1_date.setText("XXXX-XX-XX");
        forecast1_date.setPreferredSize(new java.awt.Dimension(164, 26));

        forecast1_temp.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        forecast1_temp.setForeground(new java.awt.Color(0, 51, 51));
        forecast1_temp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        forecast1_temp.setText("XX°");
        forecast1_temp.setMaximumSize(new java.awt.Dimension(100, 32));
        forecast1_temp.setMinimumSize(new java.awt.Dimension(10, 32));
        forecast1_temp.setPreferredSize(new java.awt.Dimension(100, 60));

        forecast1_icon.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout forecast1_panelLayout = new javax.swing.GroupLayout(forecast1_panel);
        forecast1_panel.setLayout(forecast1_panelLayout);
        forecast1_panelLayout.setHorizontalGroup(
            forecast1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forecast1_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(forecast1_panelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(forecast1_temp, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(forecast1_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        forecast1_panelLayout.setVerticalGroup(
            forecast1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forecast1_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(forecast1_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(forecast1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forecast1_temp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forecast1_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        forecast2_panel.setBackground(new java.awt.Color(255, 255, 255));
        forecast2_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        forecast2_panel.setForeground(new java.awt.Color(225, 230, 236));
        forecast2_panel.setPreferredSize(new java.awt.Dimension(220, 120));

        forecast2_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        forecast2_date.setForeground(new java.awt.Color(0, 51, 51));
        forecast2_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forecast2_date.setText("XXXX-XX-XX");
        forecast2_date.setPreferredSize(new java.awt.Dimension(164, 26));

        forecast2_temp.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        forecast2_temp.setForeground(new java.awt.Color(0, 51, 51));
        forecast2_temp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        forecast2_temp.setText("XX°");
        forecast2_temp.setMaximumSize(new java.awt.Dimension(100, 32));
        forecast2_temp.setMinimumSize(new java.awt.Dimension(10, 32));
        forecast2_temp.setPreferredSize(new java.awt.Dimension(100, 60));

        forecast2_icon.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout forecast2_panelLayout = new javax.swing.GroupLayout(forecast2_panel);
        forecast2_panel.setLayout(forecast2_panelLayout);
        forecast2_panelLayout.setHorizontalGroup(
            forecast2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forecast2_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(forecast2_panelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(forecast2_temp, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(forecast2_icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        forecast2_panelLayout.setVerticalGroup(
            forecast2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forecast2_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(forecast2_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(forecast2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forecast2_temp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forecast2_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        cloud_progressbar.setForeground(new java.awt.Color(0, 204, 204));
        cloud_progressbar.setToolTipText("");
        cloud_progressbar.setPreferredSize(new java.awt.Dimension(696, 30));

        humidity_progressbar.setForeground(new java.awt.Color(0, 102, 102));
        humidity_progressbar.setPreferredSize(new java.awt.Dimension(696, 30));

        humidity_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        humidity_label.setForeground(new java.awt.Color(0, 51, 51));
        humidity_label.setText("Humidity - %");
        humidity_label.setToolTipText("");
        humidity_label.setPreferredSize(new java.awt.Dimension(820, 30));

        cloud_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cloud_label.setForeground(new java.awt.Color(0, 51, 51));
        cloud_label.setText("Clouds - %");
        cloud_label.setPreferredSize(new java.awt.Dimension(820, 30));

        refresh_weather.setBackground(new java.awt.Color(255, 255, 255));
        refresh_weather.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        refresh_weather.setForeground(new java.awt.Color(111, 154, 154));
        refresh_weather.setText("Refresh");
        refresh_weather.setBorder(null);
        refresh_weather.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh_weather.setNextFocusableComponent(searchbar);
        refresh_weather.setPreferredSize(new java.awt.Dimension(110, 36));
        refresh_weather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_weatherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout weather_boxLayout = new javax.swing.GroupLayout(weather_box);
        weather_box.setLayout(weather_boxLayout);
        weather_boxLayout.setHorizontalGroup(
            weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weather_boxLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(forecast_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, weather_boxLayout.createSequentialGroup()
                            .addComponent(forecast0_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(forecast1_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(forecast2_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(humidity_progressbar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cloud_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(humidity_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cloud_progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(weather_boxLayout.createSequentialGroup()
                        .addComponent(weather_label, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refresh_weather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        weather_boxLayout.setVerticalGroup(
            weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weather_boxLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weather_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refresh_weather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cloud_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cloud_progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(humidity_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(humidity_progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(forecast_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forecast0_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forecast1_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forecast2_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tabbed_content.addTab("         Weather Dashboard                                                                                                   ", weather_box);

        typhoon_box.setBackground(new java.awt.Color(255, 255, 255));
        typhoon_box.setForeground(new java.awt.Color(255, 255, 255));
        typhoon_box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        typhoon_box.setPreferredSize(new java.awt.Dimension(918, 507));

        tc_label.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        tc_label.setForeground(new java.awt.Color(0, 51, 51));
        tc_label.setText("Latest Tropical Cyclone Advisory (PAGASA)");
        tc_label.setPreferredSize(new java.awt.Dimension(620, 38));

        typhoon_image.setToolTipText("");
        typhoon_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        typhoon_image.setPreferredSize(new java.awt.Dimension(520, 405));
        typhoon_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typhoon_imageMouseClicked(evt);
            }
        });

        tcadvisory.setBackground(new java.awt.Color(255, 255, 255));
        tcadvisory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tcadvisory.setForeground(new java.awt.Color(0, 102, 102));
        tcadvisory.setText("Latest Details");
        tcadvisory.setBorder(null);
        tcadvisory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tcadvisory.setFocusable(false);
        tcadvisory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tcadvisory.setPreferredSize(new java.awt.Dimension(138, 50));
        tcadvisory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcadvisoryActionPerformed(evt);
            }
        });

        records2021.setBackground(new java.awt.Color(255, 255, 255));
        records2021.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2021.setForeground(new java.awt.Color(0, 102, 102));
        records2021.setText("2021 Records");
        records2021.setBorder(null);
        records2021.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2021.setFocusable(false);
        records2021.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2021.setPreferredSize(new java.awt.Dimension(138, 50));
        records2021.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2021ActionPerformed(evt);
            }
        });

        records2020.setBackground(new java.awt.Color(255, 255, 255));
        records2020.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2020.setForeground(new java.awt.Color(0, 102, 102));
        records2020.setText("2020 Records");
        records2020.setBorder(null);
        records2020.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2020.setFocusable(false);
        records2020.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2020.setPreferredSize(new java.awt.Dimension(138, 50));
        records2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2020ActionPerformed(evt);
            }
        });

        records2019.setBackground(new java.awt.Color(255, 255, 255));
        records2019.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2019.setForeground(new java.awt.Color(0, 102, 102));
        records2019.setText("2019 Records");
        records2019.setBorder(null);
        records2019.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2019.setFocusable(false);
        records2019.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2019.setPreferredSize(new java.awt.Dimension(138, 50));
        records2019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2019ActionPerformed(evt);
            }
        });

        records2018.setBackground(new java.awt.Color(255, 255, 255));
        records2018.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2018.setForeground(new java.awt.Color(0, 102, 102));
        records2018.setText("2018 Records");
        records2018.setBorder(null);
        records2018.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2018.setFocusable(false);
        records2018.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2018.setPreferredSize(new java.awt.Dimension(138, 50));
        records2018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2018ActionPerformed(evt);
            }
        });

        records2017.setBackground(new java.awt.Color(255, 255, 255));
        records2017.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records2017.setForeground(new java.awt.Color(0, 102, 102));
        records2017.setText("2017 Records");
        records2017.setBorder(null);
        records2017.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        records2017.setFocusable(false);
        records2017.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records2017.setPreferredSize(new java.awt.Dimension(138, 50));
        records2017.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                records2017ActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        refresh_tropicalcyclone.setBackground(new java.awt.Color(255, 255, 255));
        refresh_tropicalcyclone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        refresh_tropicalcyclone.setForeground(new java.awt.Color(111, 154, 154));
        refresh_tropicalcyclone.setText("Refresh");
        refresh_tropicalcyclone.setBorder(null);
        refresh_tropicalcyclone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh_tropicalcyclone.setNextFocusableComponent(searchbar);
        refresh_tropicalcyclone.setPreferredSize(new java.awt.Dimension(110, 36));
        refresh_tropicalcyclone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_tropicalcycloneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typhoon_boxLayout = new javax.swing.GroupLayout(typhoon_box);
        typhoon_box.setLayout(typhoon_boxLayout);
        typhoon_boxLayout.setHorizontalGroup(
            typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typhoon_boxLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(typhoon_boxLayout.createSequentialGroup()
                        .addComponent(tc_label, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refresh_tropicalcyclone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(typhoon_boxLayout.createSequentialGroup()
                        .addComponent(typhoon_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(records2018, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(records2017, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tcadvisory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(records2021, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(records2020, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(records2019, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        typhoon_boxLayout.setVerticalGroup(
            typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typhoon_boxLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tc_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refresh_tropicalcyclone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typhoon_image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typhoon_boxLayout.createSequentialGroup()
                        .addComponent(tcadvisory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(records2021, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(records2020, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(records2019, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(records2018, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(records2017, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        tabbed_content.addTab("           Tropical Cyclone Dashboard                                                                                       ", typhoon_box);

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabbed_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sidebar_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(sidebar_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tabbed_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout content_boxLayout = new javax.swing.GroupLayout(content_box);
        content_box.setLayout(content_boxLayout);
        content_boxLayout.setHorizontalGroup(
            content_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        content_boxLayout.setVerticalGroup(
            content_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, content_boxLayout.createSequentialGroup()
                .addComponent(mainBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        content_box_scroll.setViewportView(content_box);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content_box_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(content_box_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchProcess(String area) {
        if (area.equals("")) {
            RainScape.search_area = "";
            WeatherAPI.fetch(RainScape.currentSearchArea());
        } else if (!RainScape.search_area.equals(area)){
            RainScape.search_area = area;
            WeatherAPI.fetch(RainScape.currentSearchArea());
        }
        
        WeatherAPI.setValues();
        searchbar.setText("");
        
        searchbutton.nextFocus();
    }
    
    private void hamburgerToggle(boolean active) {
        if (active) {
            line1.setBackground(Color.lightGray);
            line2.setBackground(Color.lightGray);
            line3.setBackground(Color.lightGray);
            
            if (!sidebar_box.isVisible()) {
                line4.setBackground(Color.lightGray);
                line5.setBackground(Color.lightGray);
            } else {
                line4.setBackground(menuBar.getBackground());
                line5.setBackground(menuBar.getBackground());
            }
        } else {
            line1.setBackground(line1.getForeground());
            line2.setBackground(line1.getForeground());
            line3.setBackground(line1.getForeground());
            
            if (!sidebar_box.isVisible()) {
                line4.setBackground(line1.getForeground());
                line5.setBackground(line1.getForeground());
            } else {
                line4.setBackground(menuBar.getBackground());
                line5.setBackground(menuBar.getBackground());
            }
        }
    }
    
    private void sidebarToggle() {
        if (sidebar_box.isVisible()) {
            sidebar_box.setVisible(false);
            
            line4.setBackground(Color.lightGray);
            line5.setBackground(Color.lightGray);
        } else if (!sidebar_box.isVisible()) {
            sidebar_box.setVisible(true);
            
            line4.setBackground(menuBar.getBackground());
            line5.setBackground(menuBar.getBackground());
        }
    }
    
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        LoginGUI.main(null);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void searchbarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            searchProcess(searchbar.getText());
        }
    }//GEN-LAST:event_searchbarKeyPressed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
        searchProcess(searchbar.getText());
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void hamburger_boxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMouseEntered
        // TODO add your handling code here:
        hamburgerToggle(true);
    }//GEN-LAST:event_hamburger_boxMouseEntered

    private void hamburger_boxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMouseExited
        // TODO add your handling code here:
        hamburgerToggle(false);
    }//GEN-LAST:event_hamburger_boxMouseExited

    private void hamburger_boxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMousePressed
        // TODO add your handling code here:
        hamburgerToggle(false);
    }//GEN-LAST:event_hamburger_boxMousePressed

    private void hamburger_boxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMouseReleased
        // TODO add your handling code here:
        hamburgerToggle(true);
    }//GEN-LAST:event_hamburger_boxMouseReleased

    private void hamburger_boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamburger_boxMouseClicked
        // TODO add your handling code here:
        sidebarToggle();
    }//GEN-LAST:event_hamburger_boxMouseClicked

    private void preferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferencesActionPerformed

    private void rainscapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rainscapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rainscapeActionPerformed

    private void records2021ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2021ActionPerformed
        TropicalCyclone.openOtherTCA(TropicalCyclone.tc2021);
    }//GEN-LAST:event_records2021ActionPerformed

    private void tcadvisoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcadvisoryActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Proceed to PDF Link?") == 0) {
            RainScape.openWebpage("https://pubfiles.pagasa.dost.gov.ph/tamss/weather/tcadvisory.pdf");
        }
    }//GEN-LAST:event_tcadvisoryActionPerformed

    private void typhoon_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typhoon_imageMouseClicked
        // TODO add your handling code here:
        TropicalCyclone.openBigTCA();
    }//GEN-LAST:event_typhoon_imageMouseClicked

    private void records2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2020ActionPerformed
        // TODO add your handling code here:
        TropicalCyclone.openOtherTCA(TropicalCyclone.tc2020);
    }//GEN-LAST:event_records2020ActionPerformed

    private void records2019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2019ActionPerformed
        // TODO add your handling code here:
        TropicalCyclone.openOtherTCA(TropicalCyclone.tc2019);
    }//GEN-LAST:event_records2019ActionPerformed

    private void records2018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2018ActionPerformed
        // TODO add your handling code here:
        TropicalCyclone.openOtherTCA(TropicalCyclone.tc2018);
    }//GEN-LAST:event_records2018ActionPerformed

    private void records2017ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_records2017ActionPerformed
        // TODO add your handling code here:
        TropicalCyclone.openOtherTCA(TropicalCyclone.tc2017);
    }//GEN-LAST:event_records2017ActionPerformed

    private void refresh_weatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_weatherActionPerformed
        // TODO add your handling code here:
        refresh_weather.setEnabled(false);
        
        WeatherAPI.fetch(RainScape.currentSearchArea());
        WeatherAPI.setValues();
        
        refresh_weather.setEnabled(true);
    }//GEN-LAST:event_refresh_weatherActionPerformed

    private void refresh_tropicalcycloneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_tropicalcycloneActionPerformed
        // TODO add your handling code here:
        refresh_tropicalcyclone.setEnabled(false);
        
        TropicalCyclone.fetch();

        TropicalCyclone.setValues();

        refresh_tropicalcyclone.setEnabled(true);
    }//GEN-LAST:event_refresh_tropicalcycloneActionPerformed

    private void weatherlogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weatherlogsActionPerformed
        // TODO add your handling code here:
        WeatherLogsGUI.main(null);
    }//GEN-LAST:event_weatherlogsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Dark look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println("Look and Feel Exception: " + e);
        }
        
        //</editor-fold>
        
        RainScape.access = true;
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicforecast_box;
    private javax.swing.JPanel body;
    public static javax.swing.JLabel cloud_label;
    public static javax.swing.JProgressBar cloud_progressbar;
    private javax.swing.JPanel content_box;
    private javax.swing.JScrollPane content_box_scroll;
    public static javax.swing.JLabel current_icon;
    public static javax.swing.JLabel forecast0_date;
    public static javax.swing.JLabel forecast0_icon;
    private javax.swing.JPanel forecast0_panel;
    public static javax.swing.JLabel forecast0_temp;
    public static javax.swing.JLabel forecast1_date;
    public static javax.swing.JLabel forecast1_icon;
    private javax.swing.JPanel forecast1_panel;
    public static javax.swing.JLabel forecast1_temp;
    public static javax.swing.JLabel forecast2_date;
    public static javax.swing.JLabel forecast2_icon;
    private javax.swing.JPanel forecast2_panel;
    public static javax.swing.JLabel forecast2_temp;
    private javax.swing.JLabel forecast_label;
    private javax.swing.JPanel hamburger_box;
    public static javax.swing.JLabel humidity_label;
    public static javax.swing.JProgressBar humidity_progressbar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel line1;
    private javax.swing.JPanel line2;
    private javax.swing.JPanel line3;
    private javax.swing.JPanel line4;
    private javax.swing.JPanel line5;
    public static javax.swing.JLabel localdate;
    public static javax.swing.JLabel localtime;
    public static javax.swing.JLabel location;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainBanner;
    private javax.swing.JPanel menuBar;
    private javax.swing.JButton preferences;
    private javax.swing.JButton rainscape;
    private javax.swing.JButton records2017;
    private javax.swing.JButton records2018;
    private javax.swing.JButton records2019;
    private javax.swing.JButton records2020;
    private javax.swing.JButton records2021;
    private javax.swing.JButton refresh_tropicalcyclone;
    private javax.swing.JButton refresh_weather;
    private javax.swing.JTextField searchbar;
    private javax.swing.JPanel searchbar_bg;
    private javax.swing.JButton searchbutton;
    private javax.swing.JPanel sidebar_box;
    public static javax.swing.JLabel status;
    private javax.swing.JTabbedPane tabbed_content;
    private javax.swing.JLabel tc_label;
    private javax.swing.JButton tcadvisory;
    public static javax.swing.JLabel temp;
    private javax.swing.JPanel typhoon_box;
    public static javax.swing.JLabel typhoon_image;
    private javax.swing.JPanel weather_box;
    public static javax.swing.JLabel weather_label;
    private javax.swing.JButton weatherlogs;
    // End of variables declaration//GEN-END:variables
}
